### model
model_name_or_path: /mnt/workspace/model/Meta-Llama-3-8B-Instruct/
adapter_name_or_path: /mnt/workspace/model/sft/checkpoint-4860/
template: llama3
trust_remote_code: true

### export
export_dir: /mnt/workspace/model/merge/
export_size: 2
export_device: cpu
export_legacy_format: false
